### ISSUE TITLE
OCI Bastion --> operator host --> worker nodes

### ISSUE THREAD

**Issue by denismakogon** [oracle-terraform-modules/terraform-oci-oke#330] opened 2021-08-24 09:26 UTC
At this moment, if SSH access is allowed for worker nodes, we are able to ssh into a worker node from an operator host.

Unfortunately, an ingress rule on a worker subnet is too strict:  only IP addresses from`10.0.0.0/30` are allowed. It means that we cannot SSH into the worker node from an operator host.

**Comment by hyder** [comment] 2021-08-25 00:09
Duplicate of #327

**Comment by hyder** [comment] 2021-08-25 08:52
closed in #334

**Closed by hyder** 2021-08-25 08:52 UTC
Labels: enhancement
