### ISSUE TITLE
add support for tf 13.xx

### ISSUE THREAD

**Issue by eugsim1** [oracle-terraform-modules/terraform-oci-oke#245] opened 2020-12-03 08:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

please add suppport for 13.xx terraform version

### New or Affected Resource(s)

issues with the kubernetes pool calls

**Comment by hyder** [comment] 2020-12-03 10:12
Duplicate of #241. See if you can test https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/244

**Closed** 2020-12-03 13:09 UTC
Labels: enhancement

**Comment by eugsim1** [comment] 2020-12-04 10:49
Hi tested with :
terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/oci v4.5.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

it worked perfectly for me thanks
