### ISSUE TITLE
VCN Native Networking Not Using Subnet Specified?

### ISSUE THREAD

**Issue by steve-gray** [oracle-terraform-modules/terraform-oci-oke#600] opened 2022-10-25 21:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Issue Overview

When specifying to use NPN you need to supply a VCN with at least three subnets:

- One for everything this module does
- One for the pods (a /16)
- One for the services (a /16)

This seems to be required because you can't specify a single subnet larger than a /16 , and both of the pod and services subnets must be *at least* a /16 in Kubernetes. So given my example, I allocate three subnets;

```
10.32.0.0/16 (everything else)
10.33.0.0/16 (pods)
10.34.0.0/16 (services)
```

I pass these three as the `vcn_cidrs` list into the module. However when it come to setting up node pool subnets, it appears that the subnet selected *must* be a sub-network of the 10.32/first range (as theres no provision to pass a raw subnet, and the values are all `cidrsubnet()`'d from the first subnet for all subnets.

When my pods come up, despite having NPN, they're getting 10.32 range addresses instead of 10.33? The issue appears to be there's no way to specify which of the VCN subnets into thise operation, so you end up with this operation:

```
  pods_subnet = cidrsubnet(local.vcn_cidr, lookup(var.subnets["pods"], "newbits"), lookup(var.subnets["pods"], "netnum"))`
```
... picking a subnet from the first one and mapping that as the pod subnet? 

![image](https://user-images.githubusercontent.com/14563775/197886794-a9d86f88-0b54-4353-8b3a-4bb48f35b3bd.png)
![image](https://user-images.githubusercontent.com/14563775/197887001-609ec6ee-1b78-403d-b024-3a6f818d9840.png)

Am I missing a trick here?

**Comment by hyder** [comment] 2022-10-25 23:52
Hi @steve-gray,

Thanks for logging this issue.

I think the issue is because of the way we are calculating the pods subnet here: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/modules/network/locals.tf#L10

Although you can pass a list of VCN cidrs, we always pick the first one as you can see in the comment:

```
  # first vcn cidr
  # pick the first cidr block in the list as this is where we will create the oke subnets
  vcn_cidr = element(data.oci_core_vcn.vcn.cidr_blocks, 0)
```

The additional CIDR blocks become handy if your pod count exceeds what a /16 can give you after you've provisioned subnets for other resources (workers, load balancers etc). Even then, a /16 may not be enough e.g. a worker node can host up to 110 pods and at 600 nodes, at max capacity, you've already exhausted the entire block. The way you address this is to allocate additional CIDR blocks to the VCN and eventually to more subnets. Thus, in nodepools, we have a placeholder for a list of subnet_ids but are currently picking only the subnet carved out of the VCN's 1st CIDR block:

```
https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/modules/oke/nodepools.tf#L56
```

There may be another issue here but I'll let @devoncrouse elaborate.

Do you expect to have a large number of pods?

**Comment by steve-gray** [comment] 2022-10-25 23:57
It's more that:

- You're obliged to specify a "Pods Subnet" when setting up the OKE cluster. In flannel mode, this is a virtual subnet that doesn't exist in your real VCN, and its NAT'd out to the world. 
- In NPN mode, this subnet can be a *real* subnet in your VCN.

I'd have expected a subnet to be created in the VCN using the "pods" CIDR block (as well as the "services" CIDR block) passed to the OKE cluster, and then using _that_ subnet when building the node pools in NPN mode, versus carving out a small netblock from the overarching block used for the control plane and other elements.

So I've set up security expecting pods to be on the right subnet, and instead that subnets effectively ignored.

**Comment by devoncrouse** [comment] 2022-10-26 22:44
Hi @steve-gray - you are correct, there's a [known issue](https://docs.oracle.com/en-us/iaas/Content/knownissues.htm#knownissues_topic-oke-Pod-network-connectivity-issues-on-a-VCN-with-added-CIDR-blocks) with pod subnets outside of the first VCN block, and the limitation exists outside of this project/Terraform.

The [underlying issue](https://github.com/kubernetes/kubernetes/issues/81675) relates to [KEP-2450](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2450-Remove-knowledge-of-pod-cluster-CIDR-from-iptables-rules) and [KEP-2593](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2593-multiple-cluster-cidrs), for context - the pod subnet must fall within the first block to be included in `--cluster-cidr`, and I expect this will be resolved in future Kubernetes versions.

**Closed by devoncrouse** 2022-10-26 22:44 UTC
Labels: bug

**Comment by devoncrouse** [comment] 2022-10-26 22:56
>both of the pod and services subnets must be at least a /16 in Kubernetes

Can you clarify @steve-gray? The subnets shouldn't need to be this large unless you have 65k pods/services.
