### ISSUE TITLE
terraform-oci-oke fails in base.bastion and base.operator datasources.tf files

### ISSUE THREAD

**Issue by bieksaz** [oracle-terraform-modules/terraform-oci-oke#248] opened 2020-12-14 17:08 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.12.29
terragrunt version v0.26.7
terraform-oci-oke v2.3.3

### Affected Resource(s)

terraform-oci-oke module 
modules/base.bastion/datasources.tf
modules/base.operator/datasources.tf

### Terraform Configuration Files

https://gist.github.com/bieksaz/6485ac6914add78ca18d35146f5b693a#file-oci_oke_kubectl_config2

### Plan Output

https://gist.github.com/bieksaz/7fd000709abbe2ab5bb16263ee48637e#file-gistfile1-txt

### Expected Behavior

Plan should have not thrown any errors

### Actual Behavior

errors "The given key does not identify an element in this collection value." thrown:
on .terraform/modules/base.bastion/datasources.tf line 76, in data "oci_core_vnic_attachments" "bastion_vnics_attachments"
on .terraform/modules/base.bastion/datasources.tf line 91, in data "oci_core_instance" "bastion":
on .terraform/modules/base.operator/datasources.tf line 73, in data "oci_core_vnic_attachments" "operator_vnics_attachments":
on .terraform/modules/base.operator/datasources.tf line 88, in data "oci_core_instance" "operator":

### Steps to Reproduce

run plan on terraform-oci-oke  v2.3.3 

### Important Factoids

with same configuration same scripts were working in past

**Comment by karthicgit** [comment] 2020-12-15 11:02
May I know from when its failing as you mentioned it was running fine. Can you share the terraform.tfvars excluding the auth details.

**Comment by bieksaz** [comment] 2020-12-15 13:53
@karthicgit I cant recall, when was last successful deployment, some two weeks ago or so. Last Friday when I tried it was already failing, I thought it might be related to it also being extremely slow. Did not pay much attention, thought perhaps something with OCI infrastructure, now that I tried again, its still failing and its also same slow when plan running (was never slow in past). 

I dont have terraform.tfvars. we are running terragrunt script. It deploys multiple modules, one of those is this terraform-oci-oke.
Configuration file fragment for this module I already added in "Terraform Configuration Files" section (URL to gist). I believe configurations related to other modules are unrelated here?  
Is there anything else you would need me to provide?

**Comment by karthicgit** [comment] 2020-12-17 11:28
I have tested 2.3.3 version and I am not seeing any issue . I see some changes like public_lb_ports = [80, 443] were available in terraform.tfvars which was not part of that version. the one reason I am guessing might be the image version you were using might be not available anymore in oracle cloud.

**Comment by bieksaz** [comment] 2020-12-18 08:45
so what is it that I should do now.? Something that was working all the time suddenly stopped working and you tell me that you dont see any issues.  Can we perhaps do a test run via zoom or etc like we used to do in past with your colleagues?
this public_lb_ports  variable I added some time ago and it was working with it, do not believe it may cause any trouble

**Comment by karthicgit** [comment] 2020-12-18 09:58
@bieksaz we can check via zoom . please share the zoom link if you have .

**Comment by hyder** [comment] 2020-12-18 11:43
@bieksaz It looks like it's not able to find the bastion and the operator host. Have you enabled them?

**Comment by karthicgit** [comment] 2020-12-18 12:35
> @bieksaz It looks like it's not able to find the bastion and the operator host. Have you enabled them?

@hyder  https://gist.github.com/bieksaz/6485ac6914add78ca18d35146f5b693a#file-oci_oke_kubectl_config2
They have enabled bastion and operator.

**Comment by bieksaz** [comment] 2020-12-21 07:35
hi, so what shall we do, can we agree a time for our zoom call then? for me it would be best any day somewhere 10:30 - 16:00 UTC

**Comment by karthicgit** [comment] 2020-12-21 09:41
> hi, so what shall we do, can we agree a time for our zoom call then? for me it would be best any day somewhere 10:30 - 16:00 UTC

@bieksaz We can do a zoom call @ 11AM UTC. Please share the zoom link . By the way is it ok for you to test with https://github.com/hyder/terraform-oci-oke/tree/issue-252 .

**Comment by bieksaz** [comment] 2020-12-21 11:29
https://us04web.zoom.us/j/75059212747?pwd=aWZURE9sZlpoMzhHRnpYNTErZ0FHdz09

**Comment by hyder** [comment] 2020-12-21 12:34
Quick update: we couldn't reproduce this error over zoom. So, we'll keep it open for now and monitor. 

Also, if you could share the log of the successful run as we discussed, we can then compare the difference.

Many thanks for your patience.

**Comment by bieksaz** [comment] 2020-12-21 13:17
here is todays successful plan 
https://gist.github.com/bieksaz/1df56c4f19afe17b94d398aa6c547e17#file-qh-plan-good

**Comment by hyder** [comment] 2021-01-14 00:53
@bieksaz closing this for now. If the problem happens again, please reopen so we'll have the history

**Comment by bieksaz** [comment] 2021-01-20 08:54
Dear @hyder 
Seems this issue is back again, only this time its only operator thats failing, no errors reported on bastion. 
Again very slow plan and in the end same error:    "terraform/modules/base.operator/datasources.tf line 88, in data "oci_core_instance" "operator""

**Comment by bieksaz** [comment] 2021-01-20 08:54
Should I now open a new ticket for this, or its ok to write on this same closed ticket

**Comment by hyder** [comment] 2021-01-20 09:37
I've reopened it.

**Comment by bieksaz** [comment] 2021-01-20 09:45
if you need any logs or etc just tell m, I will upload. but as far as I see it is identical issue, just that only operator involved this time

**Comment by karthicgit** [comment] 2021-01-21 12:18
@bieksaz  please share the logs and lets connect through zoom like before . Please let me know the preferred time.

**Comment by bieksaz** [comment] 2021-01-21 12:24
@karthicgit , here you will find log file from yesterdays failed plan

https://gist.github.com/bieksaz/dcdd5408dc78182a23f05e0371c61535#file-second-fail-txt

As for zoom, we could do any time  starting from UTC 13:00 (which is in 36 min). Just say when

**Comment by karthicgit** [comment] 2021-01-21 12:50
@bieksaz I see for v1.0.14 the operator datasource has 7.8 version hardcoded.Its been updated to 7.9 in recent code.
data "oci_core_images" "oracle_images" {
  compartment_id           = var.compartment_id
  operating_system         = "Oracle Linux"
  operating_system_version = "7.8"
  shape                    = var.operator_shape
  sort_by                  = "TIMECREATED"
}
Could you please check when you try to launch instances you have Oracle linux 7.8 images in your tenancy.

**Comment by bieksaz** [comment] 2021-01-21 13:21
Oracle linus 7.8 seem to exist and so does a shape we're using on AD1

Here you see our config
![image](https://user-images.githubusercontent.com/60877537/105356543-34c2cd00-5bfc-11eb-8ee8-0f1d2f91aa2d.png)

and here you see that I can pick those on our region AD1, same is for AD2 and AD3
![image](https://user-images.githubusercontent.com/60877537/105356514-2e345580-5bfc-11eb-83e3-b84330ce499e.png)

**Comment by karthicgit** [comment] 2021-01-21 13:29
@bieksaz  lets connect via zoom . please share the link

**Comment by bieksaz** [comment] 2021-01-21 13:38
need to prepare for it now, be right back

**Comment by karthicgit** [comment] 2021-01-22 15:13
Closing this issue as its an environment specific issue. There was a backend state residue which was causing the issue .

**Closed by karthicgit** 2021-01-22 15:13 UTC
Labels: bug
