### ISSUE TITLE
OKE Cluster Add-ons and Configuration

### ISSUE THREAD

**Issue by matkam** [oracle-terraform-modules/terraform-oci-oke#903] opened 2024-03-04 20:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are several add-ons available for OKE clusters in the web dashboard, as well as configuration options for each add-on. This is a feature request to add the ability to enable/disable all available add-ons, and to be able to configure them as well.

### New or Affected Resource(s)

[oci_containerengine_cluster](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_cluster#add_ons)

### Potential Terraform Configuration

```hcl
resource "oci_containerengine_cluster" "test_cluster" {
    options {
        add_ons {
            core_dns = {
                enabled = true
                configuration = {
                    min_replica = 2
                    nodes_per_replica = 25
                }
            }
        }
    }
}
```

### References

https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_cluster#add_ons

<img width="954" alt="image" src="https://github.com/oracle-terraform-modules/terraform-oci-oke/assets/578302/764e0dfe-6e3e-4b0c-9d5f-c36bd521638a">
<img width="448" alt="image" src="https://github.com/oracle-terraform-modules/terraform-oci-oke/assets/578302/62932055-e1f2-4caa-b968-c8a9a1735cac">

**Comment by hyder** [comment] 2024-03-06 02:41
Duplicate of #787

**Closed by hyder** 2024-03-06 02:41 UTC
Labels: enhancement
